name: Flask CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10  # Adjust the timeout as needed
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Flask App
      run: |
        export FLASK_APP=app.py  # Assuming app.py is the entry point for your Flask app
        export FLASK_ENV=testing
    - name: Install localtunnel
      run: |
        npm install -g localtunnel
    - name: Run App
      run: |
        nohup flask run --host=0.0.0.0 --port=5000 > flask_output.log 2>&1 &
        sleep 5
        lt --port 5000
    - name: Test App with HTTPie
      run: |
        sleep 5  # Wait for the server to fully start
        http --check-status $(cat flask_output.log | grep -o "your url" | tail -1)
